#!/usr/bin/python

# diagnostic tool

import urllib2, sys

count = int(sys.argv[1])
method = sys.argv[2]
url = sys.argv[3]

data = None
if len(sys.argv) == 5:
  data = sys.argv[4]

class MyRequest(urllib2.Request):
  def get_method(self):
    return method

req = MyRequest(url="http://localhost:1090%s" % url, data=data)
for x in range(count):
  print urllib2.urlopen(req).read()
